export { ReactComponent as LogoIcon } from './svg/logo.svg'
export { ReactComponent as CloseIcon } from './svg/close.svg'
export { ReactComponent as IncomeIcon } from './svg/income.svg'
export { ReactComponent as TotalIcon } from './svg/total.svg'
export { ReactComponent as OutcomeIcon } from './svg/outcome.svg'
